### PR TITLE
Fix KeyNotFoundException occurring to some players

### LINKED ISSUE #109: RailgunsRetargeting error after latest DSP update
I couldn't find a log with the error in it so I took a screenshot. 

6d5492acd0d6c544b6a174b2499e0ce7

### PR DESCRIPTION
**Pull request by burdoto**
Closes #109 

This PR fixes a small issue that occurred to some players after the new DSP Update.
(dont ask me why this works; it just does: https://discord.com/channels/750553061369577492/800964046383349791/864080490666131456)

### CODE REVIEW

**Comment by burdoto** [comment]
Because the error seems to be occurring to more and more people, here is a link to a working DLL that includes this fix:
[Discord Message](https://discord.com/channels/750553061369577492/800964046383349791/864078194529665034)
[File](https://cdn.discordapp.com/attachments/800964046383349791/864078194344198144/RailgunsRetargeting.dll)

File: RailgunsRetargeting/RailgunsRetargeting.cs [hunk 1]
```diff
@@ -65,18 +66,21 @@ internal static int GetEjectorUID(EjectorComponent ejector)
...
-                var managedEjector = new ManagedEjector()
+                value = new ManagedEjector
                 {
                     originalOrbitId = originalOrbitId
                 };
-                managedEjectors.Add(ejectorUID, managedEjector);
+                managedEjectors[ejectorUID] = value;
 
+                if (value == null)
+                    throw new NullReferenceException("Could not create ManagedEjector");
```
Comment (Therzok) [inline RailgunsRetargeting/RailgunsRetargeting.cs:80]: A constructor can't return null here.

File: RailgunsRetargeting/RailgunsRetargeting.cs [hunk 2]
```diff
@@ -65,18 +66,21 @@ internal static int GetEjectorUID(EjectorComponent ejector)
 
         internal static ManagedEjector GetOrCreateManagedEjector(int ejectorUID, int originalOrbitId)
         {
+            managedEjectors.TryGetValue(ejectorUID, out ManagedEjector value);
 
-            if (!managedEjectors.ContainsKey(ejectorUID))
+            if (value == null)
```
Comment (Therzok) [inline RailgunsRetargeting/RailgunsRetargeting.cs:71]: This would ensure the data would be consistent.

```csharp
if (!managedEjectors.TryGetValue(ejectorUID, out ManagedEjector value))
{
   ...
}

Comment (Therzok) [reply RailgunsRetargeting/RailgunsRetargeting.cs:71]: There is a slight problme here, GetOrCreateManagedEjector would possibly return outdated data here. There is no synchronization for accessing the value at callee site.
